[package]
name = "bevy_health_bar3d"
description = "Health bar for bevy implemented as a billboard shader"
version = "1.4.1"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["bevy", "gamedev", "healthbar", "billboard" ]
categories = ["game-development", "rendering"]
repository = "https://github.com/sparten11740/bevy_health_bar3d.git"
homepage = "https://github.com/sparten11740/bevy_health_bar3d"
authors = ["Jan Wendland"]
exclude = ["examples"]

[dependencies]
bevy = { version = "0.11.0", features = ["bevy_pbr", "bevy_render"] }
ordered-float = "3.4.0"

[dev-dependencies]
bevy-inspector-egui = "0.19.0"
bevy_tweening = "0.8.0"
